### PR TITLE
added timedatectl to linux cheatsheet

### PR DESCRIPTION
**Pull request by parth93QA**

### CODE REVIEW

**Comment by Jahenr** [comment]
Hi parth93QA

Thank you for the contribution, can you please structure the options like this: timedatectl list-timezones = List available timezones. And also please can you double check the indentation is the same as the previous entries for consistency.

Thank you
Regards
J

**Comment by parth93QA** [comment]
Have made the changes @Jahenr

**Review by parth93QA — COMMENTED** [review]
Fixed all indentation issues timedatectl

**Comment by parth93QA** [comment]
@Jahenr fixed all issues can you please verify once.

**Review by parth93QA — COMMENTED** [review]
indentation fix

**Comment by parth93QA** [comment]
@Jahenr indentation looks fine in preview but not in the file can you confirm once

**Comment by Jahenr** [comment]
Hi

I have modified the markdown how I wanted it to be structured, please have a look for future reference.
Thank you for the contribution
👍🏿

**Pull request merged**
